routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::post('/subscribe', function (){
   $email = request('email');

   Newsletter::subscribe($email);

   session()->flash('subscribed', 'Successfully subsibed');
   return redirect()->back();
});

Route::get('/', [
    'uses' => 'FrontEndController@index',
    'as' => 'index'
]);

Route::get('/results', function(){
   $posts = \App\Post::where('title', 'like', '%'.request('query').'%')->get();
    $title = "Search results: ". request('query');
    $query = request('query');

    $settings = \App\Setting::first();
    $categories = \App\Category::take(5)->get();
   return view('results', compact('posts', 'title', 'settings', 'categories', 'query'));
});

Auth::routes();

Route::get('/test', function(){
   return App\User::find(1)->profile;
});

Route::get('/post/{slug}', [
    'uses' => 'FrontEndController@singlePost',
    'as' => 'post.single'
]);

Route::get('/category/{id}', [
   'uses' => 'FrontEndController@category',
    'as' => 'category.single'
]);

Route::get('/tag/{id}', [
    'uses' => 'FrontEndController@tag',
    'as' => 'tag.single'
]);





Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function(){

    Route::get('/dashboard', 'HomeController@index')->name('home');

    Route::get('/posts/trashed', [
        'uses' => 'PostsController@trashed',
        'as' => 'posts.trashed'
    ]);
    Route::get('/posts/restore/{id}', [
        'uses' => 'PostsController@restore',
        'as' => 'posts.restore'
    ]);

    Route::get('/posts/kill/{id}', [
        'uses' => 'PostsController@kill',
        'as' => 'posts.kill'
    ]);
    Route::resource('posts', 'PostsController');

    Route::resource('categories', 'CategoriesController');
    Route::resource('tags', 'TagsController');

    Route::get('/users', [
        'uses' => 'UsersController@index',
        'as' => 'users.index'
    ]);
    Route::get('/users/create', [
        'uses' => 'UsersController@create',
        'as' => 'users.create'
    ]);
    Route::post('/users', [
        'uses' => 'UsersController@store',
        'as' => 'users.store'
    ]);
    Route::get('/users/admin/{id}', [
        'uses' => 'UsersController@admin',
        'as' => 'users.admin'
    ])->middleware('admin');
    Route::get('/users/not-admin/{id}', [
        'uses' => 'UsersController@not_admin',
        'as' => 'users.not.admin'
    ]);

    Route::get('/users/profile', [
       'uses' => 'ProfilesController@index',
        'as' => 'users.profile'
    ]);

    Route::post('/users/profile', [
        'uses' => 'ProfilesController@update',
            'as' => 'users.profile.update'
    ]);
    Route::get('/users/delete/{id}', [
        'uses' => 'UsersController@destroy',
        'as' => 'users.delete'
    ]);

    Route::get('/settings', [
        'uses' => 'SettingsController@index',
        'as' => 'settings'
    ]);

    Route::post('/settings/update', [
        'uses' => 'SettingsController@update',
        'as' => 'settings.update'
    ]);
});

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{

    protected $fillable=['tag'];

    public function posts()
    {
        return $this->belongsToMany('App\Post');
    }
}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use App\Tag;
use Illuminate\Http\Request;

class TagsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::all();
        return view('admin.tags.index', compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'tag' => 'required'
        ]);

        Tag::create([
           'tag' =>$request->tag
        ]);

        session()->flash('success', 'Tag created successfully');
        return redirect()->route('tags.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tag = Tag::find($id);
        return view('admin.tags.edit', compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
           'tag' => 'required'
        ]);

        $tag = Tag::find($id);
        $tag->tag = $request->tag;

        $tag->update();
        session()->flash('success', 'Tag updated');
        return redirect()->route('tags.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Tag::destroy($id);
        session()->flash('success', 'Tag deleted');
        return redirect()->back();

    }
}

resources/views/admin/tags/create.blade.php
@extends('layouts.app')

@section('content')

    @include('admin.includes.errors')

    <div class="panel panel-default">
        <div class="panel-heading">
            Create a new tag
        </div>
        <div class="panel-body">
            <form action="{{ route('tags.store') }}" method="POST">
                {{ csrf_field() }}

                <div class="form-group">
                    <label for="tag">Tag</label>
                    <input type="text" name="tag" id="tag" class="form-control">
                </div>


                <div class="form-group">
                    <div class="text-center">
                        <button class="btn btn-success" type="submit">Store tag</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/admin/tags/edit.blade.php
@extends('layouts.app')

@section('content')

    @include('admin.includes.errors')

    <div class="panel panel-default">
        <div class="panel-heading">
            Update category: {{ $tag->tag }}
        </div>
        <div class="panel-body">
            <form action="{{ route('tags.update', ['id' => $tag->id]) }}" method="POST">
                {{ csrf_field() }}
                <input type="hidden" name="_method" value="PUT">

                <div class="form-group">
                    <label for="tag">Tag</label>
                    <input type="text" name="tag" id="tag" value="{{ $tag->tag }}" class="form-control">
                </div>

                <div class="form-group">
                    <div class="text-center">
                        <button class="btn btn-success" type="submit">Update Tag</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/admin/tags/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="panel panel-default">
        <div class="panel-heading">
            Tags
        </div>
        <div class="panel-body">
            <table class="table table-hover">
                <thead>
                <th>Tag name</th>
                <th>Editing</th>
                <th>Deleting</th>
                </thead>
                <tbody>
                @if($tags->count()>0)
                    @foreach($tags as $tag)
                        <tr>
                            <td>{{ $tag->tag }}</td>
                            <td>
                                <a href="{{ route('tags.edit', ['id' => $tag->id]) }}" class="btn btn-info btn-xs">
                                    Edit
                                </a>
                            </td>
                            <td>
                                <form action="{{ route('tags.destroy', ['id' => $tag->id]) }}" method="POST">
                                    {{ csrf_field() }}
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="submit" class="btn btn-danger btn-xs" value="Delete">
                                </form>
                            </td>
                        </tr>
                    @endforeach
                @else
                <th>
                    <h3 class="text-center">No Tags yet</h3>
                </th>
                @endif
                </tbody>
            </table>
        </div>
    </div>

@endsection